SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    m.YEAR_MAX - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA e 
JOIN (
    SELECT 
        MAX(SIZE_OF_COLONY) AS YEAR_MAX, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON YEAR(DIFFERENTIATION_DATE)=m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;