SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.writer_id=u.user_id
WHERE b.STATUS='DONE'
GROUP BY USER_ID, NICKNAME
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES ASC;